name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest # always start with runner configuration
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # Debug the directory contents
      - name: Debug Directory Contents
        run: |
          echo "this is Current Directory: $(pwd)"
          run: ls -R
      # Set up Go 1.22
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      # Build the Go application
      - name: Build
        run: go build -o go-app-new /home/ubuntu//go-app-new
      # Run Go tests
      - name: Test
        run: go test ./...
        working-directory: /home/ubuntu/go-app-new


  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
 # till above static code analysis is done
  push:   #push into docker hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.Docker_hub_token }}

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/go-app-new:${{github.run_id}} #this tag will upddate automatically
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.general_token }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
# this part will go into the helm chartvalues.yaml and find the tag and replace it with the new tag
    - name: Commit and push changes
      run: |
        git config --global user.email "sankha.ghosh91@gmail.com"
        git config --global user.name "Sankha Ghosh"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push